# Generated by Django 4.2.28 on 2026-05-04 02:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InvestorUpdateFeed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('category', models.CharField(blank=True, help_text='e.g. Platform Update, Dev Log, Strategic Note', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_published', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MilestoneUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('completed', 'Completed'), ('ongoing', 'Ongoing'), ('planned', 'Planned')], default='planned', max_length=20)),
                ('date', models.DateField()),
                ('description', models.TextField()),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['date', 'order'],
            },
        ),
        migrations.CreateModel(
            name='InvestorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equity_percentage', models.DecimalField(decimal_places=2, help_text="Investor's equity stake in percentage", max_digits=5)),
                ('total_investment', models.DecimalField(decimal_places=2, help_text='Total amount invested', max_digits=15)),
                ('investment_date', models.DateField()),
                ('status', models.CharField(choices=[('active', 'Active'), ('pending', 'Pending'), ('exited', 'Exited')], default='active', max_length=20)),
                ('company_valuation_snapshot', models.DecimalField(blank=True, decimal_places=2, help_text='Company valuation at the time of snapshot', max_digits=15, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='investor_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='InvestmentAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('development', 'Development'), ('marketing', 'Marketing'), ('operations', 'Operations'), ('infrastructure', 'Infrastructure/Tools')], max_length=50)),
                ('allocation_percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('description_logs', models.TextField(help_text='Detailed logs of how capital was used in this category')),
                ('profile', models.ForeignKey(blank=True, help_text='Optional: link to specific investor if needed, or leave blank for global transparency', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='investors.investorprofile')),
            ],
        ),
    ]
