# Generated by Django 4.2.28 on 2026-02-15 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_vendor_approved',
            field=models.BooleanField(default=False),
        ),
    ]
