# Generated by Django 4.2.28 on 2026-03-03 05:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_brand_product_status_alter_product360video_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='brand',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vendor', to='core.brand'),
        ),
    ]
