# Generated by Django 4.2.28 on 2026-03-02 02:22

import django.utils.text
from django.db import migrations

def migrate_vendor_brands(apps, schema_editor):
    Vendor = apps.get_model('core', 'Vendor')
    Brand = apps.get_model('core', 'Brand')
    for vendor in Vendor.objects.all():
        if not vendor.brand:
            base_slug = django.utils.text.slugify(vendor.brand_name)
            if not base_slug:
                base_slug = "brand"
            slug = base_slug
            counter = 1
            while Brand.objects.filter(slug=slug).exists():
                slug = f"{base_slug}-{counter}"
                counter += 1
            brand = Brand.objects.create(name=vendor.brand_name, slug=slug)
            vendor.brand = brand
            vendor.save()

def reverse_migrate_vendor_brands(apps, schema_editor):
    pass

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_vendor_brand'),
    ]

    operations = [
        migrations.RunPython(migrate_vendor_brands, reverse_migrate_vendor_brands),
    ]
