# Generated by Django 4.2.28 on 2026-03-06 03:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_migrate_brands'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exhibition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(unique=True)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='editorial/thumbnails/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Magazine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(unique=True)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='editorial/thumbnails/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='brand',
            name='awards',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='brand',
            name='established_year',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='brand',
            name='founder_bio',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='brand',
            name='founder_image',
            field=models.ImageField(blank=True, null=True, upload_to='brands/founders/'),
        ),
        migrations.AddField(
            model_name='brand',
            name='founder_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='brand',
            name='origin_country',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='brand',
            name='philosophy',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='brand',
            name='social_links',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='brand',
            name='website',
            field=models.URLField(blank=True),
        ),
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(unique=True)),
                ('season', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField(blank=True)),
                ('hero_image', models.ImageField(blank=True, null=True, upload_to='collections/heroes/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collections', to='core.brand')),
            ],
        ),
        migrations.CreateModel(
            name='BrandImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='brands/gallery/')),
                ('caption', models.CharField(blank=True, max_length=255)),
                ('order', models.PositiveIntegerField(default=0)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery', to='core.brand')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='brand',
            name='editorial_refs',
            field=models.ManyToManyField(blank=True, related_name='brands', to='core.magazine'),
        ),
        migrations.AddField(
            model_name='brand',
            name='exhibition_refs',
            field=models.ManyToManyField(blank=True, related_name='brands', to='core.exhibition'),
        ),
    ]
