# Generated by Django 4.2.28 on 2026-03-10 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_product_care_instructions_product_fit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='featured_quote',
            field=models.CharField(blank=True, max_length=400),
        ),
        migrations.AddField(
            model_name='brand',
            name='manifesto',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='brand',
            name='story',
            field=models.TextField(blank=True),
        ),
    ]
