# Generated by Django 4.2.28 on 2026-03-10 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_brand_featured_quote_brand_manifesto_brand_story'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='editorial_quote',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='product',
            name='hero_video',
            field=models.URLField(blank=True),
        ),
    ]
