# Generated by Django 4.2.28 on 2026-03-16 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_useraddress_savedcard'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='exhibition',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='magazine',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
    ]
