# Generated by Django 4.2.28 on 2026-03-17 12:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_brand_is_featured_exhibition_is_featured_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='exhibition',
            name='statement',
            field=models.TextField(blank=True, default='Exploring the temporal intersection of architecture and human movement within the curated archive.'),
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(blank=True, help_text='HTML or Markdown content for the article body.')),
                ('magazine', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='article', to='core.magazine')),
            ],
        ),
    ]
