# Generated by Django 4.2.28 on 2026-03-17 15:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_exhibition_statement_article'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exhibition',
            name='statement',
        ),
        migrations.AddField(
            model_name='article',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='article',
            name='products',
            field=models.ManyToManyField(blank=True, related_name='featured_in_articles', to='core.product'),
        ),
        migrations.AddField(
            model_name='article',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='magazine',
            name='excerpt',
            field=models.TextField(blank=True, help_text='Short description for the magazine index page'),
        ),
        migrations.AlterField(
            model_name='article',
            name='content',
            field=models.TextField(blank=True, help_text='Full HTML content of the article'),
        ),
    ]
