# Generated by Django 4.2.28 on 2026-03-18 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_article_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='exhibition',
            name='articles',
            field=models.ManyToManyField(blank=True, related_name='exhibitions', to='core.article'),
        ),
        migrations.AddField(
            model_name='exhibition',
            name='collections',
            field=models.ManyToManyField(blank=True, related_name='exhibitions', to='core.collection'),
        ),
        migrations.AddField(
            model_name='exhibition',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='editorial/exhibitions/'),
        ),
        migrations.AddField(
            model_name='exhibition',
            name='curator_note',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='exhibition',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='exhibition',
            name='is_published',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='exhibition',
            name='magazines',
            field=models.ManyToManyField(blank=True, related_name='exhibitions', to='core.magazine'),
        ),
        migrations.AddField(
            model_name='exhibition',
            name='products',
            field=models.ManyToManyField(blank=True, related_name='exhibitions', to='core.product'),
        ),
    ]
