# Generated by Django 4.2.28 on 2026-03-18 03:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_exhibition_articles_exhibition_collections_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FitFrame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(unique=True)),
                ('cover_image', models.ImageField(upload_to='fitframes/covers/')),
                ('is_mixed', models.BooleanField(default=False)),
                ('is_featured', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fit_frames', to='core.brand')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_fits', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FitItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100)),
                ('order', models.IntegerField(default=0)),
                ('fit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='core.fitframe')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fit_items', to='core.product')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
