# Generated by Django 4.2.28 on 2026-03-19 14:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_fitframe_fititem'),
    ]

    operations = [
        migrations.CreateModel(
            name='SavedFitFrame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('fitframe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_by_users', to='core.fitframe')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_fits', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'fitframe')},
            },
        ),
    ]
