# Generated by Django 4.2.28 on 2026-03-20 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_globalcommission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='is_featured',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='order',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('shipped', 'Shipped'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], db_index=True, default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending'), ('approved', 'Approved')], db_index=True, default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='vendorearning',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('cleared', 'Cleared')], db_index=True, default='pending', max_length=20),
        ),
    ]
