# Generated by Django 4.2.28 on 2026-03-20 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_alter_brand_is_featured_alter_order_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='meta_description',
            field=models.TextField(blank=True, help_text='SEO override description', null=True),
        ),
        migrations.AddField(
            model_name='brand',
            name='meta_title',
            field=models.CharField(blank=True, help_text='SEO override title', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='collection',
            name='meta_description',
            field=models.TextField(blank=True, help_text='SEO override description', null=True),
        ),
        migrations.AddField(
            model_name='collection',
            name='meta_title',
            field=models.CharField(blank=True, help_text='SEO override title', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='exhibition',
            name='meta_description',
            field=models.TextField(blank=True, help_text='SEO override description', null=True),
        ),
        migrations.AddField(
            model_name='exhibition',
            name='meta_title',
            field=models.CharField(blank=True, help_text='SEO override title', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='magazine',
            name='meta_description',
            field=models.TextField(blank=True, help_text='SEO override description', null=True),
        ),
        migrations.AddField(
            model_name='magazine',
            name='meta_title',
            field=models.CharField(blank=True, help_text='SEO override title', max_length=255, null=True),
        ),
    ]
