# Generated by Django 4.2.28 on 2026-03-20 19:51

from django.db import migrations, models


def migrate_order_statuses(apps, schema_editor):
    Order = apps.get_model('core', 'Order')
    for order in Order.objects.all():
        old_status = order.status
        if old_status == 'pending':
            order.payment_status = 'pending'
            order.order_status = 'pending'
        elif old_status == 'paid':
            order.payment_status = 'paid'
            order.order_status = 'pending'
        elif old_status == 'shipped':
            order.payment_status = 'paid'
            order.order_status = 'shipped'
        elif old_status == 'completed':
            order.payment_status = 'paid'
            order.order_status = 'delivered'
        elif old_status == 'cancelled':
            order.order_status = 'cancelled'
            # Keep payment status as is or pending
        order.save()

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_product_meta_description_product_meta_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('shipped', 'Shipped'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], db_index=True, default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('failed', 'Failed'), ('refunded', 'Refunded')], db_index=True, default='pending', max_length=20),
        ),
        migrations.RunPython(migrate_order_statuses),
        migrations.RemoveField(
            model_name='order',
            name='status',
        ),
    ]
