# Generated by Django 4.2.28 on 2026-03-25 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_order_shipping_address_line1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='magazine',
            name='linked_articles',
            field=models.ManyToManyField(blank=True, related_name='linked_in_magazines', to='core.article'),
        ),
    ]
