# Generated by Django 4.2.28 on 2026-03-28 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_magazine_linked_articles'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='video_file',
            field=models.FileField(blank=True, help_text='Direct video upload (will be moved to Cloudinary)', null=True, upload_to='articles/videos/'),
        ),
        migrations.AddField(
            model_name='article',
            name='video_provider',
            field=models.CharField(blank=True, choices=[('youtube', 'YouTube'), ('vimeo', 'Vimeo'), ('cloudinary', 'Cloudinary')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='video_thumbnail',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='video_url',
            field=models.URLField(blank=True, help_text='YouTube, Vimeo, or Cloudinary URL', max_length=500, null=True),
        ),
    ]
