# Generated by Django 4.2.28 on 2026-03-29 03:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0038_article_video_file_article_video_provider_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='magazine',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articles', to='core.magazine'),
        ),
    ]
