# Generated by Django 4.2.28 on 2026-03-29 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0039_alter_article_magazine'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='title',
            field=models.CharField(blank=True, help_text='Optional title for the article. If not provided, magazine title will be used.', max_length=255),
        ),
    ]
