# Generated by Django 4.2.28 on 2026-03-30 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0040_article_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='slug',
            field=models.SlugField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='magazine',
            name='description',
            field=models.TextField(blank=True, help_text='Rich description for the magazine'),
        ),
    ]
