# Generated by Django 4.2.28 on 2026-04-14 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0042_article_likes_alter_article_slug_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='visibility',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AddField(
            model_name='order',
            name='paystack_reference',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
    ]
