# Generated by Django 4.2.28 on 2026-04-20 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0043_brand_visibility_order_paystack_reference'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='preview_image',
            field=models.ImageField(blank=True, null=True, upload_to='brands/previews/'),
        ),
    ]
