# Generated by Django 4.2.28 on 2026-04-20 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0044_brand_preview_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='preview_image',
            field=models.ImageField(blank=True, null=True, upload_to='collections/previews/'),
        ),
    ]
