# Generated by Django 4.2.28 on 2026-04-22 05:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0045_collection_preview_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('pwa_install', 'PWA Install'), ('signup', 'Signup'), ('checkout_start', 'Checkout Start')], db_index=True, max_length=50)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='platform_events', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
