# Generated by Django 4.2.28 on 2026-05-04 01:27

from django.db import migrations


def fix_commission_rates(apps, schema_editor):
    Vendor = apps.get_model('core', 'Vendor')
    # Reset all vendors currently at 15% to the standard 10%
    Vendor.objects.filter(commission_rate=0.15).update(commission_rate=0.10)

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0048_alter_product_editorial_quote_alter_product_fit_and_more'),
    ]

    operations = [
        migrations.RunPython(fix_commission_rates),
    ]
